"""Init table

Revision ID: b188f5e8a8f4
Revises: 
Create Date: 2021-03-13 20:18:33.491684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b188f5e8a8f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("shop", sa.String(length=100), nullable=True),
        sa.Column("payment", sa.String(length=100), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_check_date"), "check", ["date"], unique=False)
    op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["check_id"],
            ["check.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchase")
    op.drop_index(op.f("ix_check_date"), table_name="check")
    op.drop_table("check")
    op.drop_table("user")
    # ### end Alembic commands ###
