"""Init table

Revision ID: e0698f658756
Revises: 
Create Date: 2021-03-13 19:37:05.707510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0698f658756"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    shop_table = op.create_table(
        "shop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    product_table = op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    purchase_table = op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        shop_table,
        [
            {"name": "AppleStore", "address": "Some address", "phone": "8(911)111-22-33"},
            {"name": "ClothesShop", "address": "pr.Vernandskogo", "phone": "8(911)111-22-33"},
        ]
    )

    op.bulk_insert(
        product_table,
        [
            {"shop_id": 1, "name": "macbook", "description": "i5 2020 year", "price": 1500, "category": "notebook", "count": 0},
            {"shop_id": 1, "name": "iphone", "description": "a10 2019 year", "price": 1000, "category": "smartphone", "count": 0},
            {"shop_id": 2, "name": "t-shirt", "description": "regular fit", "price": 50, "category": "clothes", "count": 0}
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchase")
    op.drop_table("product")
    op.drop_table("shop")
    # ### end Alembic commands ###
