components:
  schemas:
    CreateFactory:
      properties:
        kpd:
          type: integer
        name:
          type: string
      type: object
    CreateProducts:
      properties:
        products:
          items:
            type: string
          type: array
        shop_id:
          type: integer
      type: object
    Factory:
      properties:
        id:
          type: integer
        kpd:
          nullable: true
          type: integer
        name:
          maxLength: 100
          nullable: true
          type: string
        products:
          items:
            $ref: '#/components/schemas/Product'
          type: array
      type: object
    Product:
      properties:
        count:
          nullable: true
          type: integer
        id:
          type: integer
        name:
          maxLength: 50
          nullable: true
          type: string
        shop_id:
          nullable: true
          type: integer
      type: object
info:
  title: FactoryService API
  version: 0.0.1
openapi: 3.0.0
paths:
  /api/factory/create/:
    post:
      description: Create factory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFactory'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factory'
          description: OK
        '400':
          description: Bad request
        '404':
          description: Factory already exist
        default:
          description: Unexpected error
  /api/factory/{factory_id}/order:
    post:
      description: Add products to factory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProducts'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factory'
          description: OK
        '400':
          description: Bad request
        '404':
          description: Factory not found
        default:
          description: Unexpected error
  /api/factory/{factory_id}/product:
    get:
      parameters:
      - in: path
        name: factoryID
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
          description: OK
        '400':
          description: Bad request
        '404':
          description: Factory not found
        default:
          description: Unexpected error
  /api/factory/{factory_id}:
    get:
      description: Get factory by id
      parameters:
      - in: path
        name: factoryID
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factory'
          description: OK
        '400':
          description: Bad request
        '404':
          description: Factory already exist
        default:
          description: Unexpected error
