"""empty message

Revision ID: f100c93d7ad3
Revises: 
Create Date: 2021-03-16 18:18:10.587748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f100c93d7ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    factory_table = op.create_table('factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('kpd', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    product_table = op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        factory_table,
        [
            {"name": "FactoryApple", "kpd": 10},
            {"name": "ClothesFactory", "kpd": 50},
        ]
    )

    op.bulk_insert(
        product_table,
        [
            {"shop_id": 1, "name": "macbook", "count": 0, "factory_id": 1},
            {"shop_id": 1, "name": "iphone", "count": 0, "factory_id": 1},
            {"shop_id": 2, "name": "t-shirt", "count": 0, "factory_id": 2}
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('factory')
    # ### end Alembic commands ###
